spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 976647026228082
            clientSecret: 4a5d28bce8b28a1f507061d9d579d0b0
          github:
            clientId: 7b82eb4cdffb98597940
            clientSecret: 7c57bb798e0c2d504ea47d975d772e016479b0ef
